### ISSUE TITLE
메인 화면에서 각 기능을 실행 할 수 있는 버튼 생성 

### ISSUE THREAD

**Issue by kimhye1** [kimhye1/worksone_study#2]
메인 화면에서 각 버튼을 클릭 하면 해당 기능을 실행시키는 버튼을 생성.

**Comment by soohan-jang** [comment]
## 에러 : iPhone5c iOS Version 8.3에서 오류 발생
- 9.3 버전의 시뮬레이터에서는 정상적으로 작동하는데, 8.3 버전의 테스트 디바이스에서 버튼을 클릭하면 다음과 같은 에러가 발생합니다.

<pre><code>2016-06-28 17:36:07.317 WorksOneStudy[4135:1844854] unexpected nil window in _UIApplicationHandleEventFromQueueEvent, _windowServerHitTestWindow: &lt;UIWindow: 0x17e711e0; frame = (0 0; 0 0); gestureRecognizers = &lt;NSArray: 0x17d90d90&gt;; layer = &lt;UIWindowLayer: 0x17e7a4b0&gt;&gt;</code></pre>

**Comment by soohan-jang** [comment]
## 마크다운 : &lt; &gt; 연속 사용시 해결 방법

<는 \&lt;로 >는 \&gt;로 변환해서 붙여넣으면 됩니다.

**Comment by soohan-jang** [comment]
## 오류 해결 방법
- 해당 오류가 발생하는 이유와 그에 대한 해결 방법을 전달받음.
  - AppDelegate.m 에서 스토리보드를 사용하지 않고 ViewController를 구현할 때는 ViewController를 가져온 다음 Window를 keyMakeAndVisible로 가져와야 됨. 이에 따라 코드 위치 변경이 필요.
  - 또한 9.x 버전대로 들어가면서 해당 문제가 자동으로 해결되는 것으로 보이나, 원래는 ViewController를 alloc - init할 때 단말기의 Screen Frame Size를 가져와 ViewController를 alloc - init 해야함.

**Comment by kimhye1** [comment]
확인 완료. 감사합니다 ^^
